# Generated by Django 5.0.3 on 2024-04-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_user_pending',
            name='password',
            field=models.CharField(max_length=254, verbose_name='password'),
        ),
    ]
