# Generated by Django 5.0.3 on 2024-05-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_user', '0002_user_is_admin_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_user_pending',
            name='email',
            field=models.EmailField(error_messages={'unique': 'El email ya está en uso.'}, max_length=254, unique=True),
        ),
    ]
