# Generated by Django 5.0.3 on 2024-04-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_user', '0002_alter_web_user_pending_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_user_pending',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='web_user_pending',
            name='password',
            field=models.CharField(max_length=254),
        ),
    ]
