# Generated by Django 5.0.3 on 2024-04-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_user', '0004_profile_web_user_pending_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
