# Generated by Django 5.0.3 on 2024-05-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=254)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('hours_start', models.CharField(max_length=254)),
                ('price', models.CharField(max_length=254)),
                ('packing_list', models.CharField(max_length=254)),
            ],
        ),
    ]
