# Generated by Django 5.0.3 on 2024-06-07 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('adress', models.CharField(max_length=254)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('hours_start', models.CharField(max_length=254)),
                ('price', models.CharField(max_length=254)),
                ('packing_list', models.TextField()),
                ('family_reunion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20)),
                ('allergy', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Pendiente'), (1, 'Aceptado'), (2, 'Rechazado')])),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('inscriptionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.inscriptionbase')),
            ],
            bases=('activities.inscriptionbase',),
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('inscriptionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.inscriptionbase')),
                ('image_authorization', models.BooleanField(default=False)),
                ('emergency_phone', models.CharField(max_length=20)),
                ('t_shirt_size', models.CharField(max_length=10)),
                ('medicines', models.TextField()),
            ],
            bases=('activities.inscriptionbase',),
        ),
    ]
