# Generated by Django 5.0.3 on 2024-05-21 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20)),
                ('allergy', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'activity')},
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('inscriptionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.inscriptionbase')),
            ],
            bases=('activities.inscriptionbase',),
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('inscriptionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.inscriptionbase')),
                ('cisv_authorization', models.BooleanField(default=False)),
                ('emergency_phone', models.CharField(max_length=20)),
                ('t_shirt_size', models.CharField(blank=True, max_length=10, null=True)),
                ('medicines', models.TextField()),
            ],
            bases=('activities.inscriptionbase',),
        ),
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('colaborador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.colaborador')),
                ('dni', models.CharField(max_length=9)),
                ('profession', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=100)),
                ('first_aid', models.BooleanField(default=False)),
                ('cisv_authorization', models.BooleanField(default=False)),
                ('emergency_phone', models.CharField(max_length=20)),
                ('t_shirt_size', models.CharField(blank=True, max_length=10, null=True)),
                ('medicines', models.TextField()),
            ],
            bases=('activities.colaborador',),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('colaborador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.colaborador')),
                ('dni', models.CharField(max_length=9)),
                ('languages', models.CharField(max_length=100)),
                ('cisv_authorization', models.BooleanField(default=False)),
                ('emergency_phone', models.CharField(max_length=20)),
                ('t_shirt_size', models.CharField(blank=True, max_length=10, null=True)),
                ('medicines', models.TextField()),
            ],
            bases=('activities.colaborador',),
        ),
        migrations.CreateModel(
            name='Mayores',
            fields=[
                ('participantes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.participantes')),
            ],
            bases=('activities.participantes',),
        ),
        migrations.CreateModel(
            name='Ninos',
            fields=[
                ('participantes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.participantes')),
            ],
            bases=('activities.participantes',),
        ),
    ]
