# Generated by Django 5.0.3 on 2024-05-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='family_reunion',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='adress',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='hours_start',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='packing_list',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
