# Generated by Django 5.0.3 on 2024-06-07 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionbase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cisv_safeguarding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cisv_safeguarding', to='activities.document'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='criminal_offenses_certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_offenses_certificate', to='activities.document'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='sexual_crimes_certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sexual_crimes_certificate', to='activities.document'),
        ),
        migrations.CreateModel(
            name='Mayor',
            fields=[
                ('participantes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.participantes')),
            ],
            bases=('activities.participantes',),
        ),
        migrations.CreateModel(
            name='Nino',
            fields=[
                ('participantes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.participantes')),
            ],
            bases=('activities.participantes',),
        ),
        migrations.AddField(
            model_name='participantes',
            name='health_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_card', to='activities.document'),
        ),
        migrations.AddField(
            model_name='participantes',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='activities.document'),
        ),
        migrations.AlterUniqueTogether(
            name='inscriptionbase',
            unique_together={('user', 'activity')},
        ),
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('colaborador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.colaborador')),
                ('dni', models.CharField(max_length=9)),
                ('profession', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=100)),
                ('first_aid', models.BooleanField(default=False)),
                ('image_authorization', models.BooleanField(default=False)),
                ('emergency_phone', models.CharField(max_length=20)),
                ('t_shirt_size', models.CharField(max_length=10)),
                ('medicines', models.TextField()),
                ('health_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lider_health_card', to='activities.document')),
            ],
            bases=('activities.colaborador',),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('colaborador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.colaborador')),
                ('dni', models.CharField(max_length=9)),
                ('languages', models.CharField(max_length=100)),
                ('image_authorization', models.BooleanField(default=False)),
                ('emergency_phone', models.CharField(max_length=20)),
                ('t_shirt_size', models.CharField(max_length=10)),
                ('medicines', models.TextField()),
                ('health_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_health_card', to='activities.document')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_pago', to='activities.document')),
            ],
            bases=('activities.colaborador',),
        ),
    ]
