# Generated by Django 5.0.3 on 2024-06-02 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_colaborador_cisv_safeguarding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='criminal_crimes_certificate',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='criminal_offenses_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criminal_offenses_certificate', to='activities.document'),
        ),
    ]
