# Generated by Django 5.0.3 on 2024-05-25 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_inscriptionbase_colaborador_participantes_lider_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mayores',
            new_name='Mayor',
        ),
        migrations.RenameModel(
            old_name='Ninos',
            new_name='Nino',
        ),
    ]
