# Generated by Django 5.0.3 on 2024-06-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_colaborador_criminal_crimes_certificate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lider',
            old_name='cisv_authorization',
            new_name='image_authorization',
        ),
        migrations.RenameField(
            model_name='monitor',
            old_name='cisv_authorization',
            new_name='image_authorization',
        ),
        migrations.RenameField(
            model_name='participantes',
            old_name='cisv_authorization',
            new_name='image_authorization',
        ),
    ]
