# Generated by Django 5.0.3 on 2024-06-11 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_there_are_meting_alter_lider_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionbase',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inscriptionbase',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='lider',
            name='medicines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='medicines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='medicines',
            field=models.TextField(blank=True, null=True),
        ),
    ]
