# Generated by Django 5.0.3 on 2024-06-11 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_inscriptionbase_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cisv_safeguarding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cisv_safeguarding', to='activities.document'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='criminal_offenses_certificate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criminal_offenses_certificate', to='activities.document'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='sexual_crimes_certificate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sexual_crimes_certificate', to='activities.document'),
        ),
        migrations.AlterField(
            model_name='lider',
            name='health_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lider_health_card', to='activities.document'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='health_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_health_card', to='activities.document'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_pago', to='activities.document'),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='health_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_card', to='activities.document'),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago', to='activities.document'),
        ),
    ]
