# Generated by Django 5.0.3 on 2024-06-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_rename_cisv_authorization_lider_image_authorization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionbase',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, ''), (1, ''), (2, '')], null=True),
        ),
    ]
