# Generated by Django 5.0.3 on 2024-06-16 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_colaborador_cisv_safeguarding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('colaborador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.colaborador')),
                ('profession', models.CharField(max_length=100)),
                ('pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_pago', to='activities.document')),
            ],
            bases=('activities.colaborador',),
        ),
    ]
