# Generated by Django 5.0.3 on 2024-06-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_inscriptionbase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionbase',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Pendiente'), (1, 'Aceptado'), (2, 'Rechazado')], null=True),
        ),
    ]
