# Generated by Django 5.0.3 on 2024-06-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='image_authorization',
            field=models.BooleanField(default=False),
        ),
    ]
